export default {
	INTRO: `DESTROY THINGS TO\nUPGRADE YOUR WEAPON!`,
	IDLE_HINT: `TOUCH TO MOVE`,
	CONTINUE: `CONTINUE`,
	BLOCKED: `BLOCKED!`,
	LEVEL_UP: `LEVEL UP!`,
	BALANCE: `{0} / {1}`,
	LEVEL: `LVL {0}`,
}